version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: careerforge
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./Backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/careerforge
      SECRET_KEY: supersecretkey
      ALGORITHM: HS256
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app

  frontend:
    build: ./Front-end
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8000
    volumes:
      - ./Front-end:/app
    command: npm run build && npm start
    depends_on:
      - backend

volumes:
  postgres_data: 